import "./globals.css"
import Footer from "@/components/shared/Footer"
import Header from "@/components/shared/Header"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
}

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <head />
      <body className={""}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
